spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8084
eureka:
  instance:
    preferIpAddress: true
